[general]
force_use_date = false
output_path = "C:/Users/kenji/dev/sdm_bio_vinaceous-breasted-amazon/data"
input_path = "C:/Users/kenji/dev/web-scraping-images-vinacea/web-scraping-images-vinacea/assets/"
date = "02-06-2024"
    [general.stages]
    pre_process = true
    thinning = true
    background = true
    feature_selection = true

[pre_process]
    [pre_process.files]
    file_occurence_processed = "PREP/processed_gbif.parquet"
    occurence = "PREP/occurence.parquet"
    gbif_parquet = "PREP/raw_gbif.parquet"
    [pre_process.load]
    file_occurence_unprocessed = "INPUT/gbif.csv"
    columns = ['countryCode','locality','decimalLatitude','decimalLongitude','eventDate','individualCount','basisOfRecord','collectionCode','stateProvince']
        [pre_process.load.dtype]
            'countryCode'= 'object'
            'locality'= 'object'
            'decimalLatitude'= 'float64'
            'decimalLongitude'= 'float64'
            'eventDate'= 'object'
            'individualCount'= 'int'
            'basisOfRecord'= 'object'
            'collectionCode'= 'object'
            'stateProvince'= 'object'
        [pre_process.load.columns_rename]
            "countryCode"="Pais"
            "locality"="Localizacao"
            "decimalLatitude"="lat"
            "decimalLongitude"="lon"
            "eventDate"="Data"
            "individualCount"="Contagem de individuos"
            "collectionCode"="Plataforma"
            "stateProvince"="Estado"
            "basisOfRecord"="Fonte do registro"

    [pre_process.state_encoding]
    "Santa Catarina"="SC"
    "São Paulo"="SP"
    "Rio Grande do Sul"="RS"
    "Minas Gerais"="MG"
    "Paraná"="PR"
    "Espírito Santo"="ES"
    "Brazil - São Paulo"="SP"
    "Rio de Janeiro"="RJ"
    "Brazil - Minas Gerais"="MG"
    "Bahia"="BA"
    "Mato Grosso do Sul"="MS"
    "Parana"="PR"
    "Brazil - Santa Catarina"="SC"
    "Sp"="SP"

[thinning]
    min_distance=5000
    file_thinned_data= "INPUT/occurences_filtered_{}_m.parquet"

[background]
    raster_file_path = [
        'FEATURES/TEMPERATURE/wc2.1_30s_bio_1.tif',
        'FEATURES/TEMPERATURE/wc2.1_30s_bio_2.tif',
        'FEATURES/TEMPERATURE/wc2.1_30s_bio_3.tif',
        'FEATURES/TEMPERATURE/wc2.1_30s_bio_4.tif',
        'FEATURES/TEMPERATURE/wc2.1_30s_bio_5.tif',
        'FEATURES/TEMPERATURE/wc2.1_30s_bio_6.tif',
        'FEATURES/TEMPERATURE/wc2.1_30s_bio_7.tif',
        'FEATURES/TEMPERATURE/wc2.1_30s_bio_8.tif',
        'FEATURES/TEMPERATURE/wc2.1_30s_bio_9.tif',
        'FEATURES/TEMPERATURE/wc2.1_30s_bio_10.tif',
        'FEATURES/TEMPERATURE/wc2.1_30s_bio_11.tif',
        'FEATURES/TEMPERATURE/wc2.1_30s_bio_12.tif',
        'FEATURES/TEMPERATURE/wc2.1_30s_bio_13.tif',
        'FEATURES/TEMPERATURE/wc2.1_30s_bio_14.tif',
        'FEATURES/TEMPERATURE/wc2.1_30s_bio_15.tif',
        'FEATURES/TEMPERATURE/wc2.1_30s_bio_16.tif',
        'FEATURES/TEMPERATURE/wc2.1_30s_bio_17.tif',
        'FEATURES/TEMPERATURE/wc2.1_30s_bio_18.tif',
        'FEATURES/TEMPERATURE/wc2.1_30s_bio_19.tif',
        'processed/processed/vegetacao_ibge1992_br.tif',
        'processed/processed/solos2001_br.tif',
        'processed/processed/sa2001tree_br.tif',
        'processed/processed/exposicao_br.tif',
        'processed/processed/density3_br.tif',
        'processed/processed/declividade_br.tif',
        'processed/processed/altitude_br.tif',
        'FEATURES/VEGETACAO/Cultivated_and_Managed_Vegetation.tif',
        'FEATURES/VEGETACAO/Deciduous_Broadleaf_Trees.tif',
        'FEATURES/VEGETACAO/Evergreen_Broadleaf_Trees.tif',
        'FEATURES/VEGETACAO/Herbaceous_Vegetation.tif',
        'FEATURES/VEGETACAO/Mixed_Other_Trees.tif',
        'FEATURES/VEGETACAO/Open_Water.tif',
        'FEATURES/VEGETACAO/Regularly_Flooded_Vegetation.tif',
        'FEATURES/VEGETACAO/Shrubs.tif'
    ]

    raster_file_cols = [
        'BIOVAR1',
        'BIOVAR2',
        'BIOVAR3',
        'BIOVAR4',
        'BIOVAR5',
        'BIOVAR6',
        'BIOVAR7',
        'BIOVAR8',
        'BIOVAR9',
        'BIOVAR10',
        'BIOVAR11',
        'BIOVAR12',
        'BIOVAR13',
        'BIOVAR14',
        'BIOVAR15',
        'BIOVAR16',
        'BIOVAR17',
        'BIOVAR18',
        'BIOVAR19',
        'vegetacao_ibge1992_br',
        'solos2001_br',
        'sa2001tree_br',
        'exposicao_br',
        'density3_br',
        'declividade_br',
        'altitude_br',
        'Cultivated_and_Managed_Vegetation',
        'Deciduous_Broadleaf_Trees',
        'Evergreen_Broadleaf_Trees',
        'Herbaceous_Vegetation',
        'Mixed_Other_Trees',
        'Open_Water',
        'Regularly_Flooded_Vegetation',
        'Shrubs',
        'Presence'
    ]
    n_random_points = 7_000
    random_points = false
    spacing = 10
    use_convex_polygon = true
    
[feature_selection]
threshhold = 0.7
file_feature_selection_info ='INFO/feat_selection_info.json'

[crop_files]
shape_file = "INPUT/mant_completa.shp"
source_tiff_path= '../generated_files/mantiqueira_cropped/wc2.1_30s_bio_1.tif'
update_transformation_files= [
    'vegetacao_ibge1992_br.tif',
    'solos2001_br.tif',
    'sa2001tree_br.tif',
    'exposicao_br.tif',
    'density3_br.tif',
    'declividade_br.tif',
    'altitude_br.tif'
]

[models]
selected_models = ["random_forest_class","extra_tree_class","ada_class","bagging_class","gbooster","xgb_class","lightgbm","maxent"]
test_size=  0.2
k = 5
scoring="f1_weighted"

[models_pipeline]
selected_models = ["pipeline_random_forest_class","pipeline_extra_tree_class","pipeline_ada_class","pipeline_bagging_class","pipeline_gbooster","pipeline_xgb_class","pipeline_lightgbm","pipeline_maxent"]
test_size=  0.2
k = 5
scoring="f1_weighted"